---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frpc.yoogo.top
  resources:
  - clients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frpc.yoogo.top
  resources:
  - clients/finalizers
  verbs:
  - update
- apiGroups:
  - frpc.yoogo.top
  resources:
  - clients/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - frpc.yoogo.top
  resources:
  - proxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frpc.yoogo.top
  resources:
  - proxies/finalizers
  verbs:
  - update
- apiGroups:
  - frpc.yoogo.top
  resources:
  - proxies/status
  verbs:
  - get
  - patch
  - update
